### PR TITLE
test: Add a test for ctrl_c on unix

### PR DESCRIPTION
**Pull request by Marwes**
Might be a better way of doing this but this was the best I have come up with so far. Would be nice with a test for this in any case.

### CODE REVIEW

**Comment by Marwes** [comment]
Might not be worth the hackiness actuall since this won't work on Windows anyway...

**Comment by alexcrichton** [comment]
Could a test with `harness = false` keep it self contained?

**Comment by ipetkov** [comment]
Hey @Marwes, are you still interested in applying Alex's feedback above? Just doing some housecleaning before the repo move and wanted to check the status here!

**Comment by Marwes** [comment]
Never managed to find a way to get this tested so we can just close this.

**Pull request closed without merging**
