### PR TITLE
WIP: Handler broadcast

### PR DESCRIPTION
**Pull request by vorner**
This is a proposal for #4. It is not completely finished, I'd like to discuss it first, if this is a viable approach.

The changes get rid of the restriction about the first event loop to register a signal. I believe it is async-signal safe (I use spin locks instead of mutexes and the only thing that I do inside the signal handler is `send`, which is listed as safe). However, I'm not entirely happy about that, since each `Signal` stream creates a pair of unix-domain sockets. This could use up a large number of file descriptors and I don't think it is very good performance-wise (this'd generate large number of syscalls).

If it is deemed good enough, I can finish it. If not, I'd have another proposal. I believe I'm able to create a single multiplexer task (similar to your previous `Driver` task) inside each event loop. The difference would be that each event loop would have its own one to broadcast it to its own streams, so deaths of other loops wouldn't impede it. This mechanism with multiple unix-domain sockets would be used to wake up the multiplexers. It could also use single socket and an array of `AtomicBool`s to pass on all possible signals, not one for each. That way it would be pair of sockets per event loop (which would likely be much smaller number than the number of signal streams).

I added two new dependencies, `nix` and `lazy_static`, but I believe these were indirect dependencies previously, so nothing really changes there much.

Things I still need to do:
 * Use a concrete type inside the `Signal` structure, instead of a boxed one.
 * Preserve the original sig action.
 * Go through the documentation and get rid of all the mentions about the first event loop. Instead mention the fact that each stream uses up two file descriptors.
 * Write tests for some of the internals.
 * Possibly split it into multiple sub-modules.

Furthermore, how would you feel about some small changes to interface? I preserved the current one here, but I think I could get rid of the `Future<Stream>` result of `Stream::new` and return a `Result<Stream>` directly. Also, I like the `nix`'s interface (the `Signal` enum, for example) a bit more, as it looks more „Rusty“.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'm personally pretty wary of spin locks for situations like this, they can lead to quite pathological cases. For example if the holder of a spin lock is preempted then another thread would come along and spend their entire time slice attempting to acquire the lock, when yielding is by far the best option for them. OS mutexes already handle these operations, but I don't think we can use them for signal handlers.

Thinking more on this though I think we may be able to have a reasonable approach to avoid the "one event loop" problem. In the [wait-timeout](https://github.com/alexcrichton/wait-timeout) crate I explored the strategy of basically "every signal wakes up everyone". That is essentially what happens here anyway, when a signal comes in *anyone* who may want that signal must be woken up. In that sense we can probably have some amount of cooperation here amongst all these tasks where we just wake up everything. If no one wakes up then it doesn't matter if the signal isn't processed as no one needed it anyway.

Does that make sense?

**Comment by vorner** [comment]
I agree that the spin locks aren't great in general, I just didn't see much other choice here. Anyway, even the pathological cases shouldn't be fatal and the lock being locked would be pretty rare ‒ it is locked either in the signal handler, or when adding or removing the `Signal` streams. I can't imagine people adding more than few hundred per second, because of spawned child processes. If I Implemented the second part with one stream per event loop, that would be locked mostly only during program start-up. But all in all, having to implement a private spin lock doesn't sound very elegant.

However, I'm not against other approaches. Do I read the code you link correctly as everyone trying to read from the reader-end, someone wins and then tells the others? That could work, provided we can take the same FD and plug it into multiple tokio `Core`s (I'd like to avoid duping them, for the same reasons I didn't like having so many stream pairs here). And I think this can be done by wrapping the raw FD into `EventedFd` and `PollEvented` (I hope I have the names correct). I just don't know what happens if the same FD is put into mio (and then into `epoll` or `kpoll` or `poll` or some other equivalent under the hood) multiple times. I'd rather avoid having to find out how that acts on all possible OSes. In that sense, it would probably be better to also implement the multiplexer task, so it is put into each one at most once.

But even with duping, it is not worse than this situation. So, should I try reimplementing it that way, for now?

What are you opinions on the dependencies, are they OK?

**Comment by alexcrichton** [comment]
> Do I read the code you link correctly as everyone trying to read from the reader-end, someone wins and then tells the others?

Yeah, that's the gist of it. In essence everyone has to wake up anyway, so it's all gotta happen at some point.

Good point about adding to multiple event loops! I believe epoll/kqueue handle that just fine, so it should work out a-ok to do such an operation. 

I would personally prefer to try that route before the locking route, but if it doesn't pan out we can come back here.

I'd prefer to avoid the extra dependencies, but don't let that slow you down. I can always handle them at any point basically.

**Comment by vorner** [comment]
Looking closer, at least `epoll` probably doesn`t handle it that well: https://linux.die.net/man/2/epoll_ctl. The `EEXISTS` error says:

> EEXIST op was EPOLL_CTL_ADD, and the supplied file descriptor fd is already registered with this epoll instance.

So we can't put one FD into the same `epoll` multiple times. But it should work with duping it at least.

> I'd prefer to avoid the extra dependencies, but don't let that slow you down. I can always handle them at any point basically.

I just looked and `nix` is a dependency of `mio`. So it's not really an additional dependency. The `lazy_static` is not a dependency of anything, but that one is rather small… and likely wouldn't be needed in the anycasting through a pipe scenario.

So I'll try to write it down, probably during the weekend.

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of https://github.com/alexcrichton/tokio-signal/pull/6

**Pull request closed without merging**
