### PR TITLE
Bump version to 0.2.2

### PR DESCRIPTION
**Pull request by ipetkov**
* Bump the version to 0.2.2 and prepare for a new release
* This will formally publish fixes for #36 and #38 

r + publish? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
👍

**Comment by ipetkov** [comment]
Thanks for merging @alexcrichton ! Did you get a chance to publish?

**Comment by alexcrichton** [comment]
Oh oops, sorry! I've published now

I thought you were a collab/publisher, which I've now fixed!

**Comment by ipetkov** [comment]
No worries, thanks for both! :D

--Ivan

**Pull request merged**
